version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - run:
          command: npm run lint
          name: check lint app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

# force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - build_and_test
